version: "3.7"

services:
  mysql:
    image: mariadb:10.5.9
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_USER: strapi
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_USER: strapi
  test:
    image: node:12.21.0
    volumes:
      - .:/app
    working_dir: /app
    command: /app/run-tests.sh
